GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/2
###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "eyeColor": "White",
    "name": "Felix",
    "age": 14
}
###

PUT http://localhost:5000/api/users/1

Content-Type: application/json

{
    "id": 1,
    "name": "Hanna",
}

###

DELETE http://localhost:5000/api/users/1

###