
// get all users
GET http://localhost:3000/api/users
###

// get specific user
GET http://localhost:3000/api/users/4
###


// create new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "eyeColor": "White",
    "name": "Micke",
    "age": 14
}
###

// update a user
PUT http://localhost:3000/api/users/4
Content-Type: application/json

{
    "name": "TestName",
    "age": 60
    
    
    
}

###

// delete a user
DELETE http://localhost:3000/api/users/2

###