GET http://localhost:5000/api/users

###

GET http://localhost:5000/api/users/2
###
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "eyeColor": "White",
    "name": "Hejsan",
    "age": 14
}
###

PUT http://localhost:5000/api/users/1

Content-Type: application/json

{
    "name": "Hanna",
    "eyeColor": "red",
    "age": 2
}

###

DELETE http://localhost:5000/api/users/1

###